### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by zymmiwang** [xiayouran/Musicer#13]
23.11.20 
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\Musicer-main\Musicer-main\wangyiyun\music.py", line 198, in <module>
    wyy_main()
  File "C:\Users\Administrator\Downloads\Compressed\Musicer-main\Musicer-main\wangyiyun\music.py", line 178, in wyy_main
    info_list = wyy.parse_text(id_text)
  File "C:\Users\Administrator\Downloads\Compressed\Musicer-main\Musicer-main\wangyiyun\music.py", line 119, in parse_text
    ids_list = json.loads(text)['result']['songs']
KeyError: 'result'
网易云解析失败

至于酷狗和酷我，其实在#8fix后虽然能下，但是会员的只能下载试听片段，希望改进下。

（另，作者更新太慢了啪）

**Comment by xiayouran** [comment]
精力有限更新的较慢，有假期再更新下😅欢迎提交PR哈
