### ISSUE TITLE
NetEase Musicer interface is not available

### ISSUE THREAD

**Issue by JingruiYu** [xiayouran/Musicer#7]
Great job, but the NetEase Musicer interface is not available. How to solve this problem?

`musicer) ➜  Musicer git:(main) ✗ python main.py                     

        ###   ###       ###     ###     ######    ######     ######   ########   ####### 
       ## ## ## ##      ###     ###   ###           ##     ###        ###        ##   ### 
      ##   ###   ##     ###     ###     ######      ##     ##         ########   ####### 
     ##    ###    ##    ###########         ###     ##     ###        ###        ##  ##  
    ##             ##   ###########     ######    #######   #######   ########   ##   #### 
    
目前支持的播放器类型: 1. 网易云 2. 酷狗 3. 酷我
请选择播放器类型(-1退出): 1
请输入歌名或歌手: apple
id_d: {'hlpretag': '<span class="s-fc7">', 'hlposttag': '</span>', 's': 'apple', 'type': '1', 'offset': '0', 'total': 'true', 'limit': '30', 'csrf_token': ''}
id_from_data: {'params': 'qK5a9d99NdEG5JfojTAFgQ6e37EaFWzz/hw4oEKUzFf5goOoxS9C/uCw/ABN2QK17Se2YleBtMXls+1di6uAJ2txxa0iNCaG/v7/8g39v6qGHCxoWPFij/65ZgB/GZaI3p6ZxI7bEIYG6jRcs9yHo6HHUqpCjo5y0LhUFUHlG36mpP4Mx9fSkhCHL0afds1FSr/lvKxT1j9CRXIBBf153YRDm/0ijdJxZ5umnX8n/Pek5dtsnA5yYjoFjAlv2rMLaH2J99DHoKxFVzcMvukXdju4sde/X7V89g+T8/gfdZU=', 'encSecKey': '5b7b21da497a49d514673ba3fd8a6c90bd07526a4b45a6d8d98bd0faf0012a321df9c673d4698301d31047b6accfc2848cb6823da0fe93d4d402e5a7f2211f6e390edcee6cb09032b979a8ef97106c27c4b38a06094255f6e62f67c113a1698479380cdf5fd65ee1782e470ac0f9d3249b75ada671dd0ea7bdd1cc1470925c1'}
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    select()
  File "main.py", line 21, in select
    wyy_main()
  File "/home/jryu/Music/Musicer/wangyiyun/music.py", line 176, in wyy_main
    info_list = wyy.parse_text(id_text)
  File "/home/jryu/Music/Musicer/wangyiyun/music.py", line 119, in parse_text
    ids_list = json.loads(text)['result']['songs']
  File "/home/jryu/anaconda3/envs/musicer/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/jryu/anaconda3/envs/musicer/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jryu/anaconda3/envs/musicer/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None`

**Comment by xiayouran** [comment]
Thanks for your feedback👏 The code has been updated. Please pull the latest code🙋

```python
(pytorch) λ python main.py

        ###   ###       ###     ###     ######    ######     ######   ########   #######
       ## ## ## ##      ###     ###   ###           ##     ###        ###        ##   ###
      ##   ###   ##     ###     ###     ######      ##     ##         ########   #######
     ##    ###    ##    ###########         ###     ##     ###        ###        ##  ##
    ##             ##   ###########     ######    #######   #######   ########   ##   ####

目前支持的播放器类型: 1. 网易云 2. 酷狗 3. 酷我
请选择播放器类型(-1退出): 1
请输入歌名或歌手: apple
*************************************搜索结果如下*************************************
序号　　　歌名　　　　　　　　　　　　　　　　　　歌手　　　　　　　　时长(s)　　　　　专辑　　　　　　　　　　　　　　　　　　
------------------------------------------------------------------------------------
0　　　　Apple Song　　　　　　　　　　群星　　　　　　　　77　　　　　　　　经典少儿歌曲180首　　　　　　　　　　
1　　　　APPLE　　　　　　　　　　　　　　　椎名林檎　　　　　　234　　　　　　　浮き名　　　　　　　　　　　　　　　　　
2　　　　Bad Apple!!　　　　　　　　　のみこ　　　　　　　319　　　　　　　Lovelight　　　　　　　　　　　
3　　　　Apple　　　　　　　　　　　　　　　日笠陽子　　　　　　91　　　　　　　　戦姫絶唱シンフォギアG BONUS CD オリジナルサウンド
4　　　　Bad Apple　　　　　　　　　　　Lizz Robinett282　　　　　　　Bad Apple　　　　　　　　　　　
5　　　　Apple　　　　　　　　　　　　　　　逃跑计划　　　　　　229　　　　　　　世界　　　　　　　　　　　　　　　　　　
6　　　　Apple　　　　　　　　　　　　　　　Eminem　　　　256　　　　　　　Green Lantern-mixtape
7　　　　Apple　　　　　　　　　　　　　　　テイ・トウワ　　　　236　　　　　　　94-14　　　　　　　　　　　　　　　
8　　　　Apple　　　　　　　　　　　　　　　凯瑟喵　　　　　　　155　　　　　　　罗曼史　　　　　　　　　　　　　　　　　
9　　　　転生林檎　　　　　　　　　　　　　　　　ピノキオピー　　　　219　　　　　　　転生林檎　　　　　　　　　　　　　　　　
10　　　ダンスホール　　　　　　　　　　　　　　Mrs. GREEN APPLE203　　　　　　　ダンスホール　　　　　　　　　　　　　　
11　　　那些年　　　　　　　　　　　　　　　　　胡夏　　　　　　　　371　　　　　　　那些年，我们一起追的女孩 电影原声带　　
12　　　Apple　　　　　　　　　　　　　　　bvd kult　　206　　　　　　　Apple EP　　　　　　　　　　　　
13　　　Bad Apple!! feat. nomicoのみこ　　　　　　　319　　　　　　　EXSERENS　　　　　　　　　　　　
14　　　Apple　　　　　　　　　　　　　　　Julia Michaels164　　　　　　　Inner Monologue Part 1
15　　　紅蓮華 (《鬼灭之刃》TV动画片头曲)　樱萍Apple　　　235　　　　　　　LiSA 歌曲集　　　　　　　　　　　　
16　　　僕のこと　　　　　　　　　　　　　　　　Mrs. GREEN APPLE321　　　　　　　僕のこと　　　　　　　　　　　　　　　　
17　　　Are You Ok You Can Plab Plab - Dj Apple MashApple　　　　　186　　　　　　　Apple Mash　　　　　　　　　　
18　　　only my railgun（TV动画《某科学的超电磁炮》OP1）（翻自 fripSide） 樱萍Apple　　　253　　　　　　　fripSide 歌曲集　　　　　
19　　　六哲-六哲 - 毕竟深爱过（Apple mash）（Apple remix）Apple　　　　　226　　　　　　　Apple Mash　　　　　　　　　　
********************************************************************************
请输入要下载歌曲的序号(-1退出): 0
下载完毕!
请输入要下载歌曲的序号(-1退出): -1
```
